[modules]
  [modules.preprocessor]
    name = "com.scalar.kelpie.lamb.LambPreparer"
    path = "build/libs/lamb-all.jar"
  [modules.processor]
    name = "com.scalar.kelpie.lamb.LambProcessor"
    path = "build/libs/lamb-all.jar"
  [modules.postprocessor]
    name = "com.scalar.kelpie.lamb.LambReporter"
    path = "build/libs/lamb-all.jar"

[common]
  concurrency = 1
  run_for_sec = 200
  ramp_for_sec = 10

[stats]
  realtime_report_enabled = true
  #latency_log_enabled = true

[benchmark_config]
  contract_config = "/lamb/contract_config.json"
  variable_config = "/lamb/variable_config.json"
  population_contract = "BatchCreate"
  target_contract = "Transfer"
  #population_concurrency = 32
  #num_populations = 100

[client_config]
  dl_server = "localhost"
  certificate = "/lamb/sample-keys/certificate.pem"
  private_key = "/lamb/sample-keys/private-key.pem"
