[modules]
  [modules.preprocessor]
    name = "lamb.LambPreparer"
    path = "build/libs/lamb-all.jar"
  [modules.processor]
    name = "lamb.LambProcessor"
    path = "build/libs/lamb-all.jar"
  [modules.postprocessor]
    name = "lamb.LambReporter"
    path = "build/libs/lamb-all.jar"

[common]
  concurrency = 1
  run_for_sec = 200
  ramp_for_sec = 10

[stats]
  realtime_report_enabled = true
  #latency_log_enabled = true

[test_config]
  contract_config = "./contract_list.json"
  variable_config = "./variable_configuration.json"
  population_contract = "BatchCreate"
  target_contract = "Transfer";
  #population_concurrency = 32
  #num_populations = 100

[client_config]
  dl_server = "localhost"
  certificate = "sample-keys/certificate.pem"
  private_key = "sample-keys/private-key.pem"
