[modules]
  [modules.preprocessor]
    name = "kelpie.scalardb.transfer.TransferPreparer"
    path = "build/libs/scalardb-test-all.jar"
  [modules.processor]
    name = "kelpie.scalardb.transfer.TransferProcessor"
    path = "build/libs/scalardb-test-all.jar"
  [modules.postprocessor]
    name = "kelpie.scalardb.transfer.TransferReporter"
    path = "build/libs/scalardb-test-all.jar"

[common]
  concurrency = 8
  run_for_sec = 200
  ramp_for_sec = 10

[stats]
  latency_log_enabled = true

[test_config]
  num_accounts = 100000
  population_concurrency = 8

[storage_config]
  storage = "jdbc"
  contact_points = "jdbc:postgresql://localhost:5432/postgres"
  username = "postgres"
  password = "postgres"
