[modules]
  [modules.preprocessor]
    name = "kelpie.scalardb.transfer.TransferPreparer"
    path = "build/libs/scalardb-test-all.jar"
  [modules.processor]
    name = "kelpie.scalardb.transfer.TransferProcessor"
    path = "build/libs/scalardb-test-all.jar"
  [modules.postprocessor]
    name = "kelpie.scalardb.transfer.TransferReporter"
    path = "build/libs/scalardb-test-all.jar"

[common]
  concurrency = 1
  run_for_sec = 200
  ramp_for_sec = 10

[stats]
  realtime_report_enabled = true

[test_config]
  num_accounts = 100000
  population_concurrency = 8

[storage_config]
  contact_points = "localhost"
  #username = "cassandra"
  #password = "cassandra"
  #storage = "cassandra"
  #isolation_level = "SNAPSHOT"
  #serializable_strategy = "EXTRA_READ"

[killer_config]
  ssh_user = "centos"
  ssh_port = 22
  ssh_private_key = "/home/centos/.ssh/private_key"
  contact_points = "localhost"
  max_kill_interval_sec = 300
