[modules]
  [modules.preprocessor]
    name = "kelpie.scalardb.transfer.TransferPreparer"
    path = "build/libs/scalardb-test-all.jar"
  [modules.processor]
    name = "kelpie.scalardb.transfer.WriteSkewTransferProcessor"
    path = "build/libs/scalardb-test-all.jar"
  [modules.postprocessor]
    name = "kelpie.scalardb.transfer.WriteSkewTransferChecker"
    path = "build/libs/scalardb-test-all.jar"
  [[modules.injectors]]
    name = "kelpie.scalardb.injector.CassandraKiller"
    path = "build/libs/scalardb-test-all.jar"

[common]
  concurrency = 5
  run_for_sec = 900
  ramp_for_sec = 0

[stats]
  realtime_report_enabled = false

[test_config]
  is_verification = true
  is_serializable = false
  is_extra_read = false
  num_accounts = 10
  population_concurrency = 8

[storage_config]
  contact_points = "localhost"
  #username = "cassandra"
  #password = "cassandra"
  #storage = "cassandra"
  #namespace_prefix = ""
  isolation_level = "SERIALIZABLE"
  serializable_strategy = "EXTRA_READ"

[killer_config]
  ssh_user = "centos"
  ssh_port = 22
  ssh_private_key = "/home/centos/.ssh/private_key"
  contact_points = "localhost"
  max_kill_interval_sec = 300
