[modules]
  [modules.preprocessor]
    name = "kelpie.jdbc.ycsb.Loader"
    path = "build/libs/jdbc-test-all.jar"
  [modules.processor]
    name = "kelpie.jdbc.ycsb.WorkloadF"
    path = "build/libs/jdbc-test-all.jar"
  [modules.postprocessor]
    name = "kelpie.jdbc.ycsb.YcsbReporter"
    path = "build/libs/jdbc-test-all.jar"

[common]
  concurrency = 4
  run_for_sec = 30
  ramp_for_sec = 30

[stats]
  realtime_report_enabled = true

[ycsb_config]
  record_count = 1000000
  ops_per_tx = 1
  # load_concurrency = 4
  # load_batch_size = 10

[database_config]
  url = "jdbc:postgresql://localhost:5432/ycsb"
  # url = "jdbc:mysql://localhost:3306/ycsb?useSSL=false&serverTimezone=UTC"
  username = "postgres"
  password = "postgres"
  driver = "org.postgresql.Driver"
  # driver = "com.mysql.cj.jdbc.Driver"
  min_idle = 200
  max_active = 500
